# **Exercise: Basics of Python and Numpy**

1. Import numpy and print the numpy version. (Hint: use ```__version___``` attribute to check package version.)

In [11]:
import numpy as np

np.random.seed(42)  # For reproducibility

2. Create a 4 x 5 matrix filled with random values. Name it as ```x```.

In [12]:
x = np.random.random((4,5))

print(x)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]


3. Create a 3 x 3 matrix filled with [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Name it as ```y```.

In [13]:
y = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

4. Swap the first two rows of ```x```.

In [14]:
x[[0,1]] = x[[1,0]]

print(x)

[[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]


5. Create a random numpy array with shape (100, 2) and name it ```z```. Each row indicates the coordinates of a point. Compute point by point distances.

In [27]:
z = np.random.random((100,2))
print(z)

[[0.79157904 0.78961814]
 [0.0912061  0.4944203 ]
 [0.05755876 0.54952888]
 [0.4415305  0.88770418]
 [0.35091501 0.11706702]
 [0.14299168 0.76151063]
 [0.61821806 0.10112268]
 [0.08410681 0.70096913]
 [0.07276301 0.82186006]
 [0.70624223 0.08134878]
 [0.08483771 0.98663958]
 [0.3742708  0.37064215]
 [0.81279957 0.94724858]
 [0.98600106 0.75337819]
 [0.37625959 0.08350072]
 [0.77714692 0.55840425]
 [0.42422201 0.90635439]
 [0.11119748 0.4926251 ]
 [0.01135364 0.46866064]
 [0.05630328 0.11881792]
 [0.11752625 0.6492103 ]
 [0.74604488 0.58336877]
 [0.96217255 0.37487058]
 [0.28571209 0.86859913]
 [0.22359584 0.96322254]
 [0.01215447 0.96987883]
 [0.04315991 0.89114311]
 [0.52770111 0.9929648 ]
 [0.07379656 0.55385428]
 [0.96930254 0.52309784]
 [0.62939864 0.69574869]
 [0.45454106 0.62755808]
 [0.58431431 0.90115801]
 [0.04544638 0.28096319]
 [0.95041148 0.89026378]
 [0.45565675 0.6201326 ]
 [0.27738118 0.18812116]
 [0.4636984  0.35335223]
 [0.58365611 0.07773464]
 [0.97439481 0.98621074]


In [31]:
for i in range(100):
    for j in range(100):
        if i != j:
            print(np.sqrt(np.sum((z[i] - z[j])**2)))

0.7600421170217769
0.7722879190366538
0.3635310897830605
0.8040583349159236
0.6491961166711547
0.7099859415200719
0.7130046382744326
0.7195387666746208
0.7133918009245123
0.7336898208031386
0.5913434355935229
0.1590523955423828
0.19777071679293157
0.8192020945966937
0.231663874301049
0.38545887075987517
0.742377218157698
0.843661893473859
0.9952906103147413
0.6885212667727996
0.21121592253822022
0.4484614644554759
0.511995483073423
0.5939220554343578
0.7999978581107687
0.7552738023552866
0.33313874858384235
0.7555106114874495
0.32034155076975623
0.18738718823895836
0.3739760195331675
0.23537164471321398
0.9030192759771756
0.18803534024076354
0.37625674148385585
0.7913267723498981
0.5457413871784188
0.7416266388633057
0.26845903706595237
0.27018528572815065
0.4826573319382154
0.6360400747604721
0.12380487009021367
0.17063668727803383
0.41190026267309937
0.16052138953036937
1.0675233736161815
0.4156432451765203
0.6684875387555402
0.45392051818812934
0.1859027446123152
0.32431215752037806

6. Subtract the mean of each row of ```y```.

In [51]:
y = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [52]:
y

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [57]:
np.mean(y, axis=1).reshape(-1, 1)

array([[2.],
       [5.],
       [8.]])

In [59]:
y = y - np.mean(y, axis=1).reshape(-1,1)

In [60]:
y

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

7. Add a vector [1, 0, 1] to each row of ```y``` using broadcasting and name the resulting numpy array as ```yy```.

In [61]:
yy = y + [[1,0,1]]

In [62]:
yy

array([[0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.]])

8. For each row in ```yy```, extract the value that are not equal to the other two values. Organize these values as a numpy array.

In [63]:
yy[yy>0]

array([2., 2., 2.])